name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  flutter_version: "3.24.3"
  java_version: "8.x"

jobs:
  format-and-lint:
    name: Linting and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: Install dependencies
        run: flutter pub get
      - name: Format code
        run: dart format . --set-exit-if-changed
      - name: Lint analysis
        run: flutter analyze --no-pub
      - name: Run tests
        run: flutter test --coverage
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1.2.1
        with:
          file: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
